name: CI Java
on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build & test (Maven/Gradle autodetect)
        run: |
          if [ -f "mvnw" ] || [ -f "pom.xml" ]; then
            ./mvnw -q -DskipTests clean package || mvn -q -DskipTests clean package
            ./mvnw -q test || mvn -q test || true
          elif [ -f "gradlew" ] || ls *.gradle >/dev/null 2>&1; then
            chmod +x gradlew || true
            ./gradlew build test || true
          else
            echo "No Maven/Gradle files found; skipping"
          fi
      - name: Commit CI marker (push back)
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') CI run on $GITHUB_SHA" > .ci_last_run.txt
          git add .ci_last_run.txt
          git commit -m "chore(ci): mark successful run [skip ci]" || echo "Nothing to commit"
          git push origin HEAD:${{ github.ref_name }}